language: python
matrix:
  include:
  - python: 3.5
    PARALLELIZE=false
    before_install:
      - python --version
      - pip install -U pip
      - pip install -U pytest
    script: pytest
  - python: 3.5
    PARALLELIZE=true
    before_install:
      - python --version
      - pip install -U pip
      - pip install -U pytest
    script: pytest
  - python: 3.7
    dist: xenial
    before_install:
      - python --version
      - pip install -U pip
      - pip install -U pytest
    script: pytest
  - name: "Generic Python 3.5 on macOS"
    os: osx
    language: shell  # 'language: python' is an error on Travis CI macOS
    python: 3.5
    before_install:
      - python --version
      - pip install -U pip
      - pip install -U pytest
    script: pytest
  - name: "Python 3.6.5 on macOS 10.13"
    os: osx
    osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
    language: shell  # 'language: python' is an error on Travis CI macOS
    before_install:
      - python3 --version
      - pip3 install -U pip
      - pip3 install -U pytest
      - pip3 install codecov
    script: pytest